export const routes = {
  home: '/',
  destinations: '/destinations',
  destination: (id: string) => `/destinations/${encodeURIComponent(id)}`,
  stories: '/stories',
  story: (id: string) => `/stories/${encodeURIComponent(id)}`,
  login: '/login',
  register: '/register',
  profile: '/account/profile',
  accountPosts: '/account/posts',
  newPost: '/account/posts/new',
  editPost: (id: string) => `/account/posts/${encodeURIComponent(id)}/edit`,
  accountReviews: '/account/reviews',
  managePlaces: '/manage/places',
  newPlace: '/manage/places/new',
  editPlace: (id: string) => `/manage/places/${encodeURIComponent(id)}/edit`,
  adminUsers: '/admin/users',
  adminProvinces: '/admin/provinces',
  adminCategories: '/admin/categories',
} as const;
